---
title: "Exploration Abatement Curves"
author: "David Jimenez Gonzalez"
date: '2023-08-07'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

box::use(dplyr[...],
         ggplot2[...],
         tidyr[...],
         magrittr[`%>%`],
         stringr[str_remove])
```

## Reading abatement curves


```{r}
load("../data/GCAM.Cost.Curves.Discounted.RData")

cost.curves.disc =
  cost.curves %>%
  as_tibble() %>% 
  unnest(cols = c(Region, Scenario, Year, Sector, Cost.Curve))%>%
  mutate(discounted = T)


load("../data/GCAM.Cost.Curves.Undiscounted.RData")

cost.curves.undisc =
  cost.curves %>%
  as_tibble() %>% 
  unnest(cols = c(Region, Scenario, Year, Sector, Cost.Curve))%>%
  mutate(discounted = F)


cost.curves =
  bind_rows(
    cost.curves.disc,
    cost.curves.undisc
  )


rm(cost.curves.undisc, cost.curves.disc)
```


```{r}
cost.curves %>% glimpse()
```

```{r}
cost.curves$Year%>% unique()
```
```{r}
cost.curves$Scenario%>% unique()
```
```{r}
cost.curves$Sector%>% unique()
```

```{r}
cost.curves$Region%>% unique()
```


```{r}
cost.curves %>% select(Control.Rate, Price)%>%summary()
```
```{r}
cost.curves %>%
  mutate(zero_to_one = case_when(Control.Rate<0 ~ "Negative",
                                 Control.Rate>1 ~ "Net Positive Abatement",
                                 TRUE ~ "Expected"))%>%
  group_by(Region, Scenario, Year, Sector, discounted)%>%
  summarise(inconsistency = sum(zero_to_one == "Negative" | 
                                  zero_to_one == "Net Positive Abatement")>0)%>%
  ungroup()%>%
  group_by(discounted, inconsistency)%>%
  summarise(n = n())%>%
  pivot_wider(values_from = n, names_from= inconsistency)%>%
  mutate(inconsistency_rate = `TRUE`/(`FALSE`+`TRUE`))


```

Why do we have negative Control.Rates?
Why do we have greater than 1 Control.Rates?

## Couple of curves

```{r}

cost.curves %>%
  select(Region, Scenario, Year, Sector, discounted) %>% 
  unique()%>%
  mutate(id = row_number())%>%
  sample_n(100)%>%
  left_join(cost.curves)%>%
  ggplot()+
  geom_line(aes(Control.Rate,Price, group = id), alpha = 0.1)+
  facet_grid(~discounted)
```

Why are there regressions in the abatement curves?


```{r}
total_AUC = function(x,y){
  
  n = length(x)
  
  x2 = x[-1]
  x1 = x[-n]
  y2 = y[-1]
  y1 = y[-n]
  
  sum((y1+y2)*(x2-x1)/2)
  
}

```


```{r}
cc_auc =
  cost.curves %>%
  mutate(Region = str_remove(Region,pattern = "GCAM 5.3\\+ NGFS\\|"))%>% 
  # select(Region, Scenario, Year, Sector, discounted) %>% 
  # unique()%>%
  # mutate(id = row_number())%>%
  # sample_n(100)%>%
  # left_join(cost.curves,
  #           by = c("Region", "Scenario", "Year", "Sector", "discounted"))%>%
  group_by(Region, Scenario, Year, Sector, discounted)%>%
  arrange(Control.Rate)%>%
  summarise(auc= total_AUC(Control.Rate,Price))
```

```{r}

cc_auc%>%
  ggplot()+
  geom_boxplot(aes(y = Region, x = auc))+
  scale_x_sqrt()
```

```{r}
cc_auc%>%
  ggplot()+
  geom_boxplot(aes(x = Scenario, y = auc))+
  facet_grid(~discounted)

```

```{r}
cc_auc%>%
  ggplot()+
  geom_line(
    data =. %>%
    group_by(Scenario,Year,discounted) %>%
    summarise(mid_auc = median(auc)),
    aes(x = Year, y = mid_auc ,color = Scenario))+
  facet_grid(~discounted)

```




